"""Translate src/i18n/en.ts into es.ts and hi.ts with DeepSeek V4 Flash
(Azure AI Foundry; AZURE_LLM_* in backend/.env). Only keys missing from
es.ts / hi.ts are sent, so hand fixes there are kept.

Usage: python3 scripts/translate.py"""
import json, os, re, sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import requests
from dotenv import load_dotenv

HERE = Path(__file__).resolve().parent.parent
load_dotenv(HERE.parent.parent / "backend" / ".env")
URL, KEY, MODEL = os.environ["AZURE_LLM_URL"], os.environ["AZURE_LLM_KEY"], os.environ["AZURE_LLM_MODEL"]
I18N = HERE / "src" / "i18n"
LANGS = {"es": "Spanish (neutral Latin American)", "hi": "Hindi (Devanagari, everyday spoken Hindi)"}

PROMPT = """Translate the interface strings of Banyan, an app where neighbours in small farming villages \
share spare materials, lend tools and offer skills, into {lang}.
Rules: short, plain, friendly words a villager uses; keep {{placeholders}} and <tag>...</tag> markup exactly \
(translate the text inside tags); keep "Banyan", units (KB, MB, km) and numbers; keys ending _one/_other are \
singular/plural forms. Use gender-neutral wording where the language allows.
Reply with JSON only: {{"<key>": "<translation>", ...}} for every key."""


def read(path: Path) -> dict:
    if not path.exists():
        return {}
    return dict(re.findall(r"^\s*'([^']+)':\s*(\".*?\"|'.*?'),?\s*$", path.read_text(), re.M) and
                [(k, json.loads(v) if v.startswith('"') else v[1:-1].replace("\\'", "'"))
                 for k, v in re.findall(r"^\s*'([^']+)':\s*(\".*?\"|'.*?'),?\s*$", path.read_text(), re.M)])


def ask(lang: str, batch: dict) -> dict:
    r = requests.post(f"{URL}/chat/completions", headers={"api-key": KEY}, timeout=180, json={
        "model": MODEL, "temperature": 0, "max_tokens": 8000,
        "messages": [{"role": "system", "content": PROMPT.format(lang=LANGS[lang])},
                     {"role": "user", "content": json.dumps(batch, ensure_ascii=False)}]})
    r.raise_for_status()
    text = r.json()["choices"][0]["message"]["content"]
    return json.loads(text[text.find("{"): text.rfind("}") + 1])


def main():
    en = read(I18N / "en.ts")
    for lang in LANGS:
        out_path = I18N / f"{lang}.ts"
        have = {k: v for k, v in read(out_path).items() if k in en}
        todo = {k: v for k, v in en.items() if k not in have}
        batches = [dict(list(todo.items())[i:i + 60]) for i in range(0, len(todo), 60)]
        with ThreadPoolExecutor(4) as pool:
            for res in pool.map(lambda b: ask(lang, b), batches):
                have.update({k: v for k, v in res.items() if k in en and isinstance(v, str)})
        missing = [k for k in en if k not in have]
        for k in missing:
            have[k] = en[k]  # keeps the build green; rerun to fill
        body = "".join(f"  '{k}': {json.dumps(have[k], ensure_ascii=False)},\n" for k in en)
        out_path.write_text(f"// Generated by scripts/translate.py (DeepSeek), then hand-checked. Edit freely:\n"
                            f"// reruns only fill keys that are missing here.\nimport type {{ Key }} from './en'\n\n"
                            f"const {lang}: Record<Key, string> = {{\n{body}}}\n\nexport default {lang}\n")
        print(lang, len(todo), "translated", len(missing), "still English", file=sys.stderr)


main()
